#!/usr/bin/env bash

# Initialize our own variables:
proj_dir="/vagrant"
user_name="vagrant"

user_home="/home/$user_name"

# Keep the command history.
touch "$proj_dir/.bash_history"
ln -sf "$proj_dir/.bash_history" "$user_home/.bash_history"
chown --no-dereference $user_name "$proj_dir/.bash_history" "$user_home/.bash_history"

# Aptitude packages
sudo apt-add-repository -y ppa:mc3man/trusty-media


####################################################################################
# Python 3.6.1

sudo apt-get install libssl-dev openssl
cd ~
wget https://www.python.org/ftp/python/3.6.1/Python-3.6.1.tar.xz
tar xvf Python-3.6.1.tar.xz
cd Python-3.6.1
./configure
make
sudo make install
####################################################################################


# MongoDB
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list

# Setup dependencies
sudo apt-get -y update
sudo apt-get -y install `cat $proj_dir/examples/vm/apt-packages | egrep -v "#"`

# Python packages
sudo pip3 install -r $proj_dir/examples/vm/requirements

# Set Python path to yonder projects
export PYTHONPATH=/vagrant/:/vagrant/examples/


